# Generated by Django 5.1.3 on 2025-07-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tutorgroupmeetings_studentgroupmeetings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmeetings',
            name='comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='tutorgroupmeetings',
            name='about',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='tutorgroupmeetings',
            name='theme',
            field=models.TextField(default=''),
        ),
    ]
