# Generated by Django 5.1.3 on 2025-07-09 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_studentmeetings_comment_tutorgroupmeetings_about_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorgroupmeetings',
            old_name='when',
            new_name='datetime',
        ),
        migrations.RenameField(
            model_name='tutorgroupmeetings',
            old_name='time',
            new_name='hours',
        ),
    ]
