# Generated by Django 5.1.3 on 2025-07-09 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_when_tutorgroupmeetings_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroupmeetings',
            name='meet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_group_meeting', to='api.tutorgroupmeetings'),
        ),
    ]
