# Generated by Django 5.1.3 on 2025-07-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_studentgroupmeetings_meet'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorgroupmeetings',
            name='price',
            field=models.PositiveIntegerField(default=200),
        ),
    ]
