# Generated by Django 5.1.3 on 2025-07-09 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_tutorgroupmeetings_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutormeetings',
            old_name='when',
            new_name='datetime',
        ),
    ]
