# Generated by Django 5.1.3 on 2025-07-09 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_when_tutormeetings_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmeetings',
            old_name='time',
            new_name='hours',
        ),
    ]
