# Generated by Django 5.1.3 on 2025-07-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_time_studentmeetings_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmeetings',
            name='hours',
            field=models.FloatField(),
        ),
    ]
